return {
--     "mfussenegger/nvim-lint",
--     event = { "BufReadPre", "BufNewFile" },
--     config = function()
--       local lint = require("lint")
-- 
--       lint.linters_by_ft = {
--         dockerfile = { "hadolint" },
--         cpp = { "clangtidy", "cppcheck" },
--         sh = { "shellcheck" },
--       }
-- 
-- --      lint.linters = {
-- --        cppcheck = function()
-- --          local cppcheck = require("lint").linters.cppcheck
-- --          -- Add the --project argument
-- --          table.insert(cppcheck.args, 1, "--inline-suppr -q -rp --enable=warning --project=compile_commands.json")
-- --          return cppcheck
-- --        end,
-- --      },
-- 
--       local lint_augroup = vim.api.nvim_create_augroup("lint", { clear = true })
-- 
--       vim.api.nvim_create_autocmd({ "BufEnter", "BufWritePost", "InsertLeave" }, {
--         group = lint_augroup,
--         callback = function()
--           lint.try_lint()
--         end,
--       })
-- 
--       vim.keymap.set("n", "<leader>l", function()
--         lint.try_lint()
--       end, { desc = "Trigger linting for current file" })
--     end,
  }
