# starship.toml

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
palette = "default"

format = """
[╭](fg:separator)\
$os\
$directory\
$git_status\
$git_branch\
$line_break\
[╰](fg:separator)\
$character\
"""

###########################################

[palettes.default]
prompt_ok  = "#8047c1"
prompt_err = "#e23140"
icon       = "#161514"
separator  = "#35312c"
background = "#35312c"

directory  = "#9f31e2"
duration   = "#e26f31"
status     = "#e23140"

###########################################

[os.symbols]
Ubuntu = "󰕈 "
Linux = " "
# Docker = ""

###########################################

[os]
format = "[─](fg:separator)[](fg:directory)[$symbol](fg:icon bg:directory)[](fg:directory)"
disabled = false

[character]
success_symbol = "[❯](fg:prompt_ok)"
error_symbol = "[❯](fg:prompt_err)"

[directory]
format = "[─](fg:separator)[](fg:directory)[ ](fg:icon bg:directory)[](fg:directory bg:background)[ $path](bg:background)[](fg:background)"
truncate_to_repo = true
truncation_length = 1
truncation_symbol = './'

[git_status]
format = "[-](fg:separator)[](fg:directory)[$ahead_behind$staged$renamed$deleted$modified$untracked ](fg:icon bg:directory)"
deleted = ' 󱂥 ${count}'
modified = ' 󰷉 ${count}'
renamed = '  ${count}'
untracked = '  ${count}'
staged = '  ${count}'
ahead = '⇡${count}'
behind = ' ⇣${count}'
diverged = '⇡${ahead_count}:⇣${behind_count}'

[git_branch]
format = "[ ](fg:directory bg:background)[$branch](bg:background)[](fg:background)"
truncation_length = 20

[status]
format = "[─](fg:separator)[](fg:status)[](fg:icon bg:status)[](fg:status bg:background)[ $status](bg:background)[](fg:background)"
pipestatus = true
pipestatus_separator = "-"
pipestatus_segment_format = "$status"
pipestatus_format = "[─](fg:separator)[](fg:status)[](fg:icon bg:status)[](fg:status bg:background)[ $pipestatus](bg:background)[](fg:background)"
disabled = false

[cmd_duration]
format = "[─](fg:separator)[](fg:duration)[󱦟](fg:icon bg:duration)[](fg:duration bg:background)[ $duration](bg:background)[](fg:background)"
min_time = 0

[time]
format = "[-](fg:separator)[](fg:duration)[ ](fg:icon bg:duration)[](fg:duration bg:background)[ $time](bg:background)[](fg:background)"
disabled = false
